version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Install dependencies
python:
  install:
    - requirements: docs/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
